config/routes.rb
Rails.application.routes.draw do
  root to: 'application#welcome'
  get 'carts/:id' => "carts#show", as: "cart"
  delete 'carts/:id' => "carts#destroy"

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  get 'line_items/:id' => "line_items#show", as: "line_item"
  delete 'line_items/:id' => "line_items#destroy"

  resources :categories do
    resources :items
  end
  resources :menus do 
    resources :items
  end
  resources :items
  resources :orders
  
  get 'users/show'
  get '/users/:id', to: 'users#show'
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/sign_out' => 'devise/sessions#destroy'
    get '/signup', to: 'devise/registrations#new'
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :items, through: :line_items

    def sub_total
        sum = 0
        self.line_items.each do |line_item|
            sum += line_item.total_price
        end
        sum
    end
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :items
    has_many :menus, through: :items
    validates :name, presence: true
    validates :name, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :category, optional: true
    belongs_to :menu, optional: true
    belongs_to :order, optional: true
    belongs_to :cart, optional: true
    has_many :line_items, dependent: :destroy
    validates :name, presence: true
    validates :price, presence: true
    validates :description, presence: true

    # validates :menu_id, presence: true, blank: false, nil: false
    # validates :category_id, presence: true, blank: false, nil: false

    def self.by_menu(menu_id)
        where(menu: menu_id)
    end

    def self.by_category(category_id)
        where(category: category_id)
    end
    
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item, optional: true
  belongs_to :cart, optional: true
  belongs_to :order, optional: true

    def total_price
      self.quantity * self.item.price
    end
end

app/models/menu.rb
class Menu < ApplicationRecord
    has_many :items
    has_many :categories, through: :items
    validates :name, presence: true
    validates :name, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :items, through: :line_items
    belongs_to :user, optional: true
    validates :name, :email, :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, 
          :rememberable, :validatable

  has_many :orders
  has_one :cart
  has_many :items, through: :orders
  has_many :items, through: :cart
  validates :name, presence: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

    def current_items
      self.cart.items
    end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :authenticate_user!
    def show
        @cart = @current_cart
    end

    def destroy
        @cart = @current_cart
        @cart.destroy
        session[:cart_id] = nil
        redirect_to root_path
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]
    before_action :admin_only, except: [:index, :show]
    before_action :find_item
    def index
        @menus = Menu.all 
        @categories = Category.all

        @items = Item.where(nil)
        @items = @items.by_menu(params[:menu]) if params[:menu].present?
        @items = @items.by_category(params[:category]) if params[:category].present?
    end

    def new
        @item = Item.new
    end

    def create
        @item = Item.new(item_params)
        if @item.save
            redirect_to item_path(@item), notice: "You've successfully created a new item!"
        else
            render :new
        end
    end

    def show

    end

    def edit
    end

    def update
        @item.update(item_params)
        if @item.save
            redirect_to item_path(@item), notice: "You've successfully updated an item!"
        else
            render :edit
        end
    end

    def destroy
        @item.destroy
        redirect_to items_path, notice: "You've successfully deleted an item!"
    end

private

    def find_item
        @item = Item.find_by(id: params[:id])
    end

    def item_params
        params.require(:item).permit(:name, :price, :menu_id, :category_id, :cart_id, :order_id, :description)
    end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    before_action :find_menu, only: [:show, :edit, :update]
    before_action :authenticate_user!
    before_action :admin_only

    def index
        @menus = Menu.all
    end

    def new
        @menu = Menu.new
    end

    def create
        @menu = Menu.new(menu_params)
        if @menu.save
            redirect_to menu_path(@menu), notice: "You have successfully created a menu!"
        else 
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        @menu.update(menu_params)
        if @menu.save
            redirect_to menu_path(@menu), notice: "You have successfully updated a menu!"
        else
            render :edit
        end
    end

    def destroy
        @menu.destroy
        redirect_to menus_path, notice: "You have successfully deleted a menu."
    end

private
    def find_menu
        @menu = Menu.find_by(id: params[:id])
    end

    def menu_params
        params.require(:menu).permit(:name)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find_by(id: params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = current_user.orders.new(order_params)
    @current_cart.line_items.each do |item|
      @order.line_items << item
      item.cart_id = nil
    end
    @order.save
    Cart.destroy(session[:cart_id])
    session[:cart_id] = nil
    redirect_to root_path, notice: "You've successfully created an order!"
  end
  
  private
    def order_params
      params.require(:order).permit(:name, :email, :address, :pay_method, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
    def items 
        @items.first
    end

end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/orders_helper.rb
module OrdersHelper


    def created_at(order)
        order.created_at.strftime("%B %e, %Y at %l:%M %p")
    end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<header class="break">
<h2><%= current_user.name %>'s Cart</h2>
</header>
<p><%= button_to "Back to Menu", items_path, method: :get %></p>
<ol>
    <% @cart.line_items.each do |line_item| %>
    <li>Item: <%= line_item.item.name %></li>
    Price: <%= number_to_currency(line_item.item.price) %><br>
    Quantity: <%= line_item.quantity %><br>
    Total Price: <%= number_to_currency(line_item.total_price) %><br>

    <%= button_to "Add one", line_item_add_path(:id => line_item), method: :post %>
    <%= button_to "Reduce one", line_item_reduce_path(:id => line_item), method: :post %>
    <%= button_to "Remove item", line_item_path(line_item), method: :delete %>
    <br>
    <% end %>
</ol>
<h3>Sub total: $<%= @cart.sub_total %></h3>

<% if @cart.line_items.count > 0 %>
<%= button_to "Proceed to checkout", new_order_path, method: :get %>
<% end %>
<br>
<%= button_to "Empty cart", cart_path(@current_cart), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/items/_form.html.erb
<%= form_for item do |f| %>
    <label>Menu:</label>
    <%= f.collection_select :menu_id, Menu.all, :id, :name, include_blank: true%>
    <br>
    <label>Category:</label>
    <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true%>
    <br>
    <label>Item Name:</label>
    <%= f.text_field :name, class: "field_with_errors" %>
    <br>
    <%= f.label :price %>
    <%= f.number_field :price, value: number_to_currency(f.object.price.to_f, delimiter: '', unit: ''), step: :any %>
    <br>
    <%= f.label :description %>
    <%= f.text_area :description %>
    <br>
    <%= f.submit %>
<% end %>

app/views/items/_links.html.erb
<p><%= button_to "Add New Item", new_item_path, method: :get %></p>
<p><%= button_to "Edit Item", edit_item_path(item), method: :get %></p>
<p><%= button_to "Delete Item", item_path(item), method: :delete %></p>

app/views/items/edit.html.erb
<header class="break">
<h2>Edit Item</h2>
</header>

<%= render partial: 'categories/errors', locals: {resource: @item} %>

<%= render partial: 'form', locals: {item: @item} %>

app/views/items/index.html.erb
<header class="break">
<h2>Menu</h2>
</header>
<% if user_signed_in? %>
    <% if current_user.admin %>
        <h5>----- Admin -----</h5>
        <p><%= button_to "Go Back Menu List", menus_path, method: :get %></p>
        <p><%= button_to "Go Back Category List", categories_path, method: :get %></p>
        <h5>------ Only ------</h5>
    <% end %>
<% end %>

<h3>Filter Items by Menu and Category</h3>
<div class="filter">
<%= form_tag("/items", method: "get") do %>
    <label>Menu</label>
    <%= select_tag "menu", options_from_collection_for_select(@menus, :id, :name), include_blank: true %>
    <label>Category</label>
    <%= select_tag "category", options_from_collection_for_select(@categories, :id, :name), include_blank: true %>
    <%= submit_tag "Filter"%>
<% end %>
</div>

<% @items.each do |item| %>
    <div>
        <p><%= link_to item.name, item_path(item) %></p>
    </div>
<% end %>

app/views/items/new.html.erb
<header class="break">
<h2>Create a New Item</h2>
</header>
<%= render partial: 'categories/errors', locals: {resource: @item} %>


<%= render partial: 'form', locals: {item: @item} %>

app/views/items/show.html.erb
<header class="break">
<h2><%= @item.menu.name %></h2>
</header>
<%= button_to "Back to Menu", items_path, method: :get %>
<h3><%= @item.category.name %></h3>
<h4>Item Name: <%= @item.name %></h4>
<h4>Price: $<%= @item.price %></h4>
<p><%= @item.description %></p>



<% if user_signed_in?%>
    <%= button_to "Add to Cart", line_items_path(:item_id => @item.id) %>
    <% if current_user.admin %>
        <h5>----- Admin -----</h5>
        <%= render partial: 'links', locals: {item: @item} %>
        <h5>----- Only ------</h5>
    <% end %>
<% end %>

app/views/menus/_form.html.erb
<%= form_for resource do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.submit %>
<% end %>

app/views/menus/_links.html.erb
<p><%= button_to "View All Items", menu_items_path(menu), method: :get %></p>
<p><%= button_to "Add New Items", new_menu_item_path(menu), method: :get %></p>
<p><%= button_to "Edit Menu Name", edit_menu_path(menu), method: :get %></p>
<p><%= button_to "Delete Menu Name", menu_path(menu), method: :delete %></p>

app/views/menus/edit.html.erb
<header class="break">
<h2>Edit Menu</h2>
</header>

<%= render partial: 'categories/errors', locals: {resource: @menu} %>

<%= render partial: 'form', locals: {resource: @menu} %>

app/views/menus/index.html.erb
<header class="break">
<h2>Welcome to our Menu</h2>
</header>



<% @menus.each do |menu| %>
    <p><%= link_to menu.name, menu_path(menu) %></p>
<% end %>


<p><%= button_to "Add New Menu", new_menu_path, method: :get %></p>

app/views/menus/new.html.erb
<header class="break">
<h2>Add a New Menu Name</h2>
</header>

<%= render partial: 'categories/errors', locals: {resource: @menu} %>


<%= render partial: 'form', locals: {resource: @menu} %>

app/views/menus/show.html.erb
<header class="break">
<h2><%= @menu.name %></h2>
</header>


<% @menu.items.each do |item| %>
    <p><%= link_to item.name, menu_item_path(@menu, item) %></p>
<% end %>

<%= render partial: 'links', locals: {menu: @menu} %>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name, required: true, autofocus: true %>
    </p>
    <p>
        <%= f.label :email %><br>
        <%= f.email_field :email %>
    </p>
    <p>
        <%= f.label :address %><br>
        <%= f.text_area :address %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/orders/index.html.erb
<header class="break">
<h2>All Orders</h2>
</header>


<% @orders.each do |order| %>
    <p>Name: <%= order.name %></p>
    <p>Email: <%= order.email %></p>
    <p>Line Items: </p>
    <ul>
    <% order.line_items.each do |item| %>
        <li><%= item.quantity %> x <%= item.product.name %></li>
    <% end %>
    </ul>
<% end

app/views/orders/new.html.erb
<header class="break">
<h2>New Order</h2>
</header>

<%= render partial: 'categories/errors', locals: {resource: @order} %>

<%= render partial: 'form', locals: {order: @order} %>

app/views/orders/show.html.erb
<header class="break">
<h2>Order created on <%= created_at(@order) %></h2>
</header>
<ol>
<% @order.items.each do |item| %>
    <li><%= item.name %></li>
    <p><%= item.description %></p>
<% end %>
</ol>

app/views/users/show.html.erb
<header class="break">
<h2>Welcome, <%= current_user.name %></h2>
</header>


<h4>My Orders</h4>

<% current_user.orders. each do |order| %>
    <p><%= link_to created_at(order), order_path(order) %></p>
<% end %>